#!/bin/bash

# shellcheck source=../lib/utils
source ./src/lib/utils

# shellcheck source=../lib/packages
source ./src/lib/packages

stow_configuration() {
  local package=$1
  local target=$2
  if help_arg "$1"; then
    echo "Usage: stow_configuration"
    echo "destroys files that are not symbolic links or directories"
    return
  fi


  stow_destroy_conflicts "$PACKAGE_DIR/$package" "$target"
  stow --dir="$PACKAGE_DIR" --target="$target" "$package"
}

stow_destroy_conflicts() {
  local package_dir=$1
  local target=$2
  if help_arg "$1"; then
    echo "Usage: stow_destroy_conflicts"
    echo "destroys files that are not symbolic links or directories"
    return
  fi
  shopt -u dotglob
  for entry in "/$package_dir/"*; do
    entry=$target/$(basename "$entry")
    if [[ -e "$entry" ]] && ! [[ -d "$entry" ]] && ! [[ -L "$entry" ]]; then
      echo "❗ $entry exists and is not a symlink, removing"
      rm -rf "$entry"
    fi
    if [ ! -e "$1" ] && [ -h "$1" ]; then
      echo "❗ $entry exists and but the link is broken, removing"
      rm -rf "$entry"
    fi
  done
}