#!/bin/bash

terminal_colors() {
    for i in {0..255}; do
        printf "\x1b[48;5;%sm%3d\e[0m " "$i" "$i"
        if ((i == 15)) || ((i > 15)) && (((i - 15) % 6 == 0)); then
            printf "\n"
        fi
    done
}

set_github_token() {
    unset GITHUB_TOKEN
    if ! gh auth status &>/dev/null; then
        gh auth login -h github.com
    fi
    token="$(gh config get -h github.com oauth_token)"
    export GITHUB_TOKEN="$token"
}

cs_actions_dev() {
    name=$(gh cs create -r github/github -b master)
    gh cs ssh -c $name -- "cd /workspaces/github && script/setup-codespaces-actions"
    gh cs code -c $name
}
