brew "macvim"
brew "sipcalc"
brew "nmap"
brew "whois"
brew "shellcheck"
brew "stow"
brew "antigen"
brew "tmux"
brew "svn"
brew "azure-cli"
brew "go"
brew "mas"
brew "coreutils"
brew "lastpass-cli"

cask "obsidian"
cask "docker"
cask "amethyst"
cask "google-chrome"
cask "vagrant"
cask "vagrant-manager"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "microsoft-office"
cask "font-source-code-pro-for-powerline"
cask "slack"
cask "alfred"
cask "little-snitch"
cask "micro-snitch"
cask "homebrew/cask-drivers/displaylink"
cask "notion"
cask "zoom"
cask "textual"
cask "microsoft-teams"
cask "spotify"
cask "anaconda"
cask "signal"
cask "telegram-desktop"


mas "Bear", id: 1091189122 
