session_name: default
windows:
  - window_name: scratch
    layout: tiled
    shell_command_before:
      - cd ~/ # run as a first command in all panes
    panes:
      - echo 
      - echo
  - window_name: dotfiles
    layout: tiled
    shell_command_before:
      - cd ~/.dotfiles # run as a first command in all panes
    panes:
      - nvim
