#!/bin/bash
# shellcheck source=../lib/utils
source ./src/lib/utils

# shellcheck source=../lib/setup
source ./src/lib/setup

DOTFILES_DIR=/workspaces/.codespaces/.persistedshare/dotfiles

export DOTFILES_DIR

define PKGLIST <<EOF
  stow
  zsh
  tmux
  python3-pip
  fzf
EOF
export PKGLIST

function bootstrap() {
  sudo apt-get update
  xargs sudo apt-get install -y <<<"$PKGLIST"
  pip install --user tmuxp
}

function is_bootstrapped() {
  while read -r pkg; do
    if ! dpkg -l "$pkg" &>/dev/null; then
      echo "$pkg is"
      return 1
    fi
  done <<<"$PKGLIST"
  return 0
}

function setup() {
  setup_git
  setup_fzf
  setup_zsh
  zsh_first_time_setup
  setup_tmux
  mark_setup_successful
}
