#!/usr/bin/env bash
# shellcheck source=../lib/utils
source ./src/lib/utils

# shellcheck source=../lib/setup
source ./src/lib/setup

# validate cached sudo credentials if not running in CI
if [ -z "${CI+x}" ]; then
  sudo -v
fi

export DOTFILES_DIR=$HOME/ghq/github.com/nodeselector/dotfiles

function bootstrap() {
  eval "$(/opt/homebrew/bin/brew shellenv)"
  if ! type -P brew >/dev/null; then
    CI=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  fi
  /opt/homebrew/bin/brew analytics off
  # /opt/homebrew/bin/brew bundle install
  defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false
  defaults write NSGlobalDomain KeyRepeat -int 2
  defaults write NSGlobalDomain InitialKeyRepeat -int 15
  defaults write "Apple Global Domain" com.apple.sound.beep.volume -int 0
  
  if ! test -e /usr/local/bin/leader; then
    curl -L --output /tmp/leader https://github.com/dhamidi/leader/releases/download/v0.3.2/leader.darwin.amd64
    chmod +x /tmp/leader
    sudo mv /tmp/leader /usr/local/bin/leader
  fi

}

function is_bootstrapped() {
  brew update
  brew outdated >/dev/null
  test -e /usr/local/bin/leader
}

function setup() {
  setup_common
  setup_hammerspoon
}
