#!/bin/bash
CALLED_DIR=$(pwd)
on_exit() {
    cd "$CALLED_DIR"
}
trap on_exit EXIT

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && cd .. && pwd)"
export DOTFILES_DIR

export SCRIPT_DIR="$DOTFILES_DIR"/script
export DOTFILES_LIB="$SCRIPT_DIR/utils/dotfiles.lib.sh"

# shellcheck source=utils
[ -f "$DOTFILES_LIB" ] && source "$DOTFILES_LIB"

user_help() {
    echo "nodeselector's dotfiles"
    echo
    echo "Syntax: dotfiles (help | clean | setup | reload | bootstrap | clean)"
    echo "options:"
    echo "reload                Reload dotfiles. Do this when you change stuff."
    echo "setup                 Run this for initial setup. Note, it doesn't remove dependencies."
    echo "bootstrap             Install or update dependencies"
    echo "clean                 Remove dotfiles from home directory."
    echo "macos                 Run macos system configuration."
    echo
    exit
}

if ! [[ $# -eq 1 ]]; then
    user_help
fi

case $1 in
reload) echo "🔃 reloading dots" && reload ;;
setup) echo "🚀 running setup" && setup ;;
bootstrap) echo "📦️🥾 installing dependencies" && bootstrap ;;
clean) echo "🧹🧼 cleaning" && reset ;;
macos) echo "🍎 setting up your macos configuration" && "$DOTFILES_DIR/.macos" ;;
help) user_help ;;
*) echo "Invalid option: $1" && user_help ;;
esac
