#!/usr/bin/env bash
# target files must declare these functions:
# bootstrapped: return true if bootstrapped, false otherwise
# bootstrap: install dependencies needed in target
# setup: take care of any other setup
#
# it must also export a DOTFILES_DIR
#
# optionally, any exported variable beginning in DOTFILES_
# will be added to zshrc.local

# shellcheck source=../src/lib/utils
source ./src/lib/utils
set -eE -o functrace

TMP_ERRS=$(mktemp)
trap 'failure $TMP_ERRS' ERR

main() {
  echo "👋 hi there, ${GITHUB_USER:=nodeselector}"
  if target_is_macos; then
    echo "🍎 macos runtime detected"

    # shellcheck source=../src/targets/macos
    source ./src/targets/macos
  elif target_is_codespaces; then
    echo "💻 codespaces runtime detected"
    export TARGET="Codespaces"

    # shellcheck source=../src/targets/codespaces
    source ./src/targets/codespaces
  elif target_is_ubuntu; then
    echo "💻 ubuntu runtime detected"
    export TARGET="Ubuntu"

    # shellcheck source=../src/targets/ubuntu
    source ./src/targets/ubuntu
  else
    echo "👽 unknown runtime, send help"
    exit 1
  fi

  validate_target_configuration "$DOTFILES_DIR" "$TARGET"

  if ! is_bootstrapped; then
    echo "🥾 bootstrapping necessary"
    bootstrap
  else
    echo "🥾 bootstrapping uneccessary"
  fi

  echo "🏎️  starting setup" # fast emojis make computers run faster
  setup
}

main
