#!/bin/bash

quiet_git() {
    stdout=$(mktemp)
    stderr=$(mktemp)

    if ! git "$@" </dev/null >"$stdout" 2>"$stderr"; then
        cat "$stderr" >&2
        rm -f "$stdout" "$stderr"
        exit 1
    fi

    rm -f "$stdout" "$stderr"
}

reset() {
    stow --delete --dir="$DOTFILES_DIR" --target="$HOME" zsh
    stow --delete --dir="$DOTFILES_DIR" --target="$HOME" tmux
    stow --delete --dir="$DOTFILES_DIR" --target="$HOME" git
    stow --delete --dir="$DOTFILES_DIR" --target="$HOME" hammerspoon
}

reload() {
    stow --restow --dir="$DOTFILES_DIR" --target="$HOME" zsh
    stow --restow --dir="$DOTFILES_DIR" --target="$HOME" tmux
    stow --restow --dir="$DOTFILES_DIR" --target="$HOME" git
    stow --restow --dir="$DOTFILES_DIR" --target="$HOME" hammerspoon
}

bootstrap() {
    # shellcheck source=bootstrap
    source "$SCRIPTS_DIR/bootstrap"
}

init_stow() {
    touch ~/.zshrc.local
    stow --dir="$DOTFILES_DIR" --target="$HOME" zsh
    stow --dir="$DOTFILES_DIR" --target="$HOME" tmux
    tmux start-server
    tmux source ~/.tmux.conf

    stow --dir="$DOTFILES_DIR" --target="$HOME" git
}

setup() {
    reset
    init_stow
    bootstrap
    if ! [ "$SHELL" == "/bin/zsh" ]; then
        sudo chsh -s /bin/zsh "$USER"
    fi
    if [[ "$UNAME" == 'Darwin' ]]; then
        ## Hammerspoon
        rm -rf ~/.hammerspoon/Spoons/*
        mkdir -p ~/.hammerspoon/Spoons
        quiet_git clone https://github.com/jasonrudolph/ControlEscape.spoon.git ~/.hammerspoon/Spoons/ControlEscape.spoon
    fi
}
