#!/bin/bash

BRAIN_PATH="$HOME/src/github.com/nodeselector/brain"
timestamp="$(date "+%Y%m%d%H%M")"

cd "$BRAIN_PATH"

fleeting() {
	read -p "label this thought: " title
	if [[ -z "$title" ]]; then
		exit 0
	fi
	nvim "+set laststatus=0" "$BRAIN_PATH/fleeting/${timestamp}_${title}.md"
}

literature() {
	echo "New literature note"
	timestamp="$(date "+%Y%m%d%H%M")"
	read -p "title: " title
	read -p "url: " url
	export LITERATURE_TEMPLATE=$(cat <<EOF

----
[1]: $url

EOF
)
	if [[ -z "$title" ]]; then
		exit 0
	fi

	echo "$LITERATURE_TEMPLATE" | nvim "+set laststatus=0" "$BRAIN_PATH/literature/${timestamp}_${title}.md"
}

follow_up() {
	read -p "what: " what
	PS3='when: '
	options=("Today" "Tomorrow" "This Week" "Someday")
	select opt in "${options[@]}"
	do
			case $opt in
					"Today")
						  when="today"
							break
							;;
					"Tomorrow")
						  when="tomorrow"
							break
							;;
					"This Week")
						  when="this_week"
							break
							;;
					"Someday")
						  when="someday"
							break
							;;
					*) 
							when="uncategorized"
							break
						  ;;
			esac
	done
	nvim "$BRAIN_PATH/followup/${when}/${timestamp}_${what}.md"
}

picker() {
	PS3='Please enter your choice: '
	options=("Fleeting" "Follow up" "Literature" "Quit")
	select opt in "${options[@]}"
	do
			case $opt in
					"Fleeting")
						fleeting
						break
							;;
					"Follow up")
						follow_up
						break
							;;
					"Literature")
						literature
						break
							;;
					"Quit")
							break
							;;
					*) echo "K, bai";;
			esac
	done
}

picker
