#!/bin/bash

TPM_DIR="$HOME/.tmux/plugins/tpm"
VUNDLE_DIR="$HOME/.vim/bundle/Vundle.vim"
UNAME=$(uname)

if [[ "$UNAME" == 'Darwin' ]]; then
	if ! type -P brew >/dev/null; then
		CI=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
	fi
	brew analytics off
	brew bundle

elif [[ "$UNAME" == 'Linux' ]]; then
	sudo apt-get -y install zsh whois sipcalc dnsutils stow
	if [[ "$USER" == 'build' ]]; then
		sudo chsh -s $(which zsh) build
	fi
fi

# TPM
if [[ -d "$TPM_DIR" ]]; then
	sudo rm -r "$TPM_DIR"
fi

quiet_git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# Vundle
if [[ -d "$VUNDLE_DIR" ]]; then
	sudo rm -r "$VUNDLE_DIR"
fi
quiet_git clone https://github.com/VundleVim/Vundle.vim.git "$VUNDLE_DIR"
