#!/bin/bash
CALLED_DIR=$(pwd)
on_exit() {
    cd "$CALLED_DIR"
}
trap on_exit EXIT

DOTFILES_DIR="$HOME"/.dotfiles
SCRIPTS_DIR="$DOTFILES_DIR"/scripts
UTILS="$SCRIPTS_DIR"/utils

# shellcheck source=utils
[ -f "$UTILS" ] && source "$UTILS"

user_help() {
    echo "nodeselector's dotfiles"
    echo
    echo "Syntax: dotfiles (--help | --clean | --setup | --reload | --bootstrap | --clean)"
    echo "options:"
    echo "reload                Reload dotfiles. Do this when you change stuff."
    echo "setup                 Run this for initial setup. Note, it doesn't remove dependencies."
    echo "bootstrap             Install or update dependencies"
    echo "clean                 Remove dotfiles from homedirectory."
    echo
    exit
}

if ! [[ $# -eq 1 ]]; then
    user_help
fi

case $1 in
reload) echo "🔃 reloading dots" && reload ;;
setup) echo "🚀 running setup" && setup ;;
bootstrap) echo "📦️🥾 installing dependencies" && cd "$DOTFILES_DIR" && bootstrap ;;
clean) echo "🧹🧼 cleaning" && reset ;;
help) user_help ;;
*) echo "Invalid option: $1" && user_help ;;
esac
