#!/bin/bash
quiet_git() {
    stdout=$(mktemp)
    stderr=$(mktemp)
    
    if ! git "$@" </dev/null >"$stdout" 2>"$stderr"; then
        cat "$stderr" >&2
        rm -f "$stdout" "$stderr"
        exit 1
    fi
    
    rm -f "$stdout" "$stderr"
}

DOTFILES_DIR=~/dotfiles
DNS_SERVERS='9.9.9.9 149.112.112.112'
DARWIN_PRIMARY_CONNECTION='Wi-Fi'

#########
# Set DNS Servers
#########

sudo networksetup -setdnsservers $DARWIN_PRIMARY_CONNECTION $DNS_SERVERS

#########
# Install Dependencies
#########

source "$DOTFILES_DIR/scripts/bootstrap"

#########
# zsh
#########

if ! [ "$SHELL" == "/bin/zsh"  ]; then
    sudo chsh -s /bin/zsh "$USER"
fi


stow --dir="$DOTFILES_DIR" --target="$HOME" zsh

#########
# tmux
#########


stow --dir="$DOTFILES_DIR" --target="$HOME" tmux
tmux start-server
tmux source ~/.tmux.conf

#########
# Vim
#########

stow --dir="$DOTFILES_DIR" --target="$HOME" vim
vim +BundleInstall +qall

#########
# Alfred
#########

rm -rf "$HOME/src/alfred"
git clone git@github.com:nodeselector/alfred.git "$HOME/src/alfred"
