#!/bin/bash
log() {
    printf "$2\n"
    syslog -s -l "$1" "$2"
}

quiet_git() {
    stdout=$(mktemp)
    stderr=$(mktemp)
    
    if ! git "$@" </dev/null >$stdout 2>$stderr; then
        cat $stderr >&2
        rm -f $stdout $stderr
        exit 1
    fi
    
    rm -f $stdout $stderr
}

DOTFILES_DIR=~/dotfiles
DNS_SERVERS='9.9.9.9 149.112.112.112'
DARWIN_PRIMARY_CONNECTION='Wi-Fi'

#########
# Set DNS Servers
#########

log info "Setting $DNS_SERVERS as DNS servers on connection $DARWIN_PRIMARY_CONNECTION"
sudo networksetup -setdnsservers $DARWIN_PRIMARY_CONNECTION $DNS_SERVERS

#########
# Install Dependencies
#########

log info "Running bootstrap script"
source $DOTFILES_DIR/scripts/bootstrap

#########
# zsh
#########

if ! [ $SHELL == "/bin/zsh"  ]; then
    sudo chsh -s /bin/zsh $USER
fi


stow --dir=$HOME/dotfiles --target=$HOME zsh

#########
# tmux
#########


stow --dir=$HOME/dotfiles --target=$HOME tmux
tmux start-server
tmux source ~/.tmux.conf

#########
# Vim
#########

stow --dir=$HOME/dotfiles --target=$HOME vim
vim +BundleInstall +qall

#########
# Alfred
#########

rm -rf "$DOTFILES_DIR/alfred"
git submodule add --force git@github.com:nodeselector/alfred.git "$DOTFILES_DIR/alfred"
