#!/bin/bash
set -e

# shellcheck source=utils
[ -f "$UTILS" ] && source "$UTILS"
trap on_exit EXIT

DOTFILES_DIR="$HOME"/src/dotfiles
SCRIPTS_DIR="$DOTFILES_DIR"/scripts
UTILS="$SCRIPTS_DIR"/utils

setup
