#!/bin/bash

DOTFILES_DIR="$HOME"/.dotfiles
SCRIPTS_DIR="$DOTFILES_DIR"/scripts
UNAME=$(uname)

quiet_git() {
    stdout=$(mktemp)
    stderr=$(mktemp)

    if ! git "$@" </dev/null >"$stdout" 2>"$stderr"; then
        cat "$stderr" >&2
        rm -f "$stdout" "$stderr"
        exit 1
    fi

    rm -f "$stdout" "$stderr"
}

reset() {
    stow --delete --dir="$DOTFILES_DIR" --target="$HOME" zsh
    stow --delete --dir="$DOTFILES_DIR" --target="$HOME" vim
    stow --delete --dir="$DOTFILES_DIR" --target="$HOME" tmux
    stow --delete --dir="$DOTFILES_DIR" --target="$HOME" git
}

reload() {
    stow --restow --dir="$DOTFILES_DIR" --target="$HOME" zsh
    stow --restow --dir="$DOTFILES_DIR" --target="$HOME" vim
    stow --restow --dir="$DOTFILES_DIR" --target="$HOME" tmux
    stow --restow --dir="$DOTFILES_DIR" --target="$HOME" git
}

bootstrap() {
    # shellcheck source=bootstrap
    source "$SCRIPTS_DIR/bootstrap"
}

init_stow() {
    touch ~/.zshrc.local
    stow --dir="$DOTFILES_DIR" --target="$HOME" zsh
    stow --dir="$DOTFILES_DIR" --target="$HOME" tmux
    tmux start-server
    tmux source ~/.tmux.conf

    stow --dir="$DOTFILES_DIR" --target="$HOME" vim
    vim +BundleInstall +qall

    stow --dir="$DOTFILES_DIR" --target="$HOME" git
}

setup() {
    reset
    init_stow
    bootstrap
    if ! [ "$SHELL" == "/bin/zsh" ]; then
        sudo chsh -s /bin/zsh "$USER"
    fi
    if [[ "$UNAME" == 'Darwin' ]]; then
        ## Hammerspoon
        rm -rf ~/.hammerspoon/Spoons/*
        mkdir -p ~/.hammerspoon/Spoons
        git clone https://github.com/jasonrudolph/ControlEscape.spoon.git ~/.hammerspoon/Spoons/ControlEscape.spoon
        stow --dir="$DOTFILES_DIR" --target="$HOME/.hammerspoon" hammerspoon

        ## MacOS General Configuration
        "$DOTFILES_DIR/.macos"

    elif [[ "$UNAME" == 'Linux' ]]; then
        MACHINE_MODEL=$(sudo dmidecode | grep 'Version:' | sudo dmidecode | grep 'SKU Number' | head -1 | awk '{ print $4 }')
        if [[ "$MACHINE_MODEL" == 'P52s' ]]; then
            gsettings set org.gnome.desktop.peripherals.touchpad send-events disabled
        fi
    fi
}
