#!/bin/bash
# shellcheck source=../lib/utils
source ./script/lib/utils

# shellcheck source=../lib/setup
source ./script/lib/setup

if [ "$CODESPACES_VSCODE_FOLDER" = "/workspaces/dotfiles" ]; then
  DOTFILES_DIR=/workspaces/.codespaces/.persistedshare/dotfiles
else
  DOTFILES_DIR=/workspaces/dotfiles
fi

export DOTFILES_DIR

define PKGLIST <<EOF
  stow
  zsh
  tmux
  python3-pip
EOF
export PKGLIST

function bootstrap() {
  sudo apt-get update
  xargs sudo apt-get install -y <<<"$PKGLIST"
  pip install --user tmuxp
}

function is_bootstrapped() {
  # shellcheck disable=SC2162 # TODO figure if needed
  while read pkg; do
    if ! dpkg -l "$pkg" &>/dev/null; then
      return 1
    fi
  done <<<"$PKGLIST"
  return 0
}

function setup() {
  setup_git
  setup_zsh
  setup_tmux
}
