# Naive test of dotfiles. Success is a 0 return code. That's it.
name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_vm:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Run setup script
      run: ./setup.sh
  test_container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run setup script
      run: docker build .